// ignore_for_file: lines_longer_than_80_chars, document_ignores

import 'package:flutter/material.dart';

/// Official-ish color palette for Georg Fischer IoT & Electronics (approx.).
///
/// *Primary* is derived from the corporate “GF Blue 1” (Pantone 300 C ≈ #0072B3)  📈
/// The rest of the palette is generated by tonal shifts of that hue plus neutral greys
/// inspired by the visual identity shown on georgfischer.com.
///
/// NOTE: Hex values were matched by sampling the GF logo and cross‑checking against
/// public mentions of *GF Blue 1 Pantone*; tweak if you obtain the official guideline.

const Color _gfBlue = Color(0xFF0072B3); // GF Blue 1   (primary)
const Color _gfBlueDark = Color(
  0xFF004A7D,
); // shade‑800   (inversePrimary for dark)
const Color _gfBlue60 = Color(
  0xFF66B1E3,
); // 60 % tint   (primaryContainer on light)

const Color _neutral98 = Color(0xFFF8F9FB); // near‑white surface on light
const Color _neutral10 = Color(0xFF191C1E); // near‑black surface on dark
const Color _neutral80 = Color(0xFFC5C7C8); // greys for text in dark mode

/// Light theme – white surfaces, GF blue accents.
const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: _gfBlue,
  onPrimary: Colors.white,
  primaryContainer: _gfBlue60,
  onPrimaryContainer: Color(0xFF001F2E),
  secondary: Color(0xFF4C616B),
  onSecondary: Colors.white,
  secondaryContainer: Color(0xFFE0ECF3),
  onSecondaryContainer: Color(0xFF121C22),
  tertiary: Color(0xFF006772), // teal accent used in IoT visuals
  onTertiary: Colors.white,
  tertiaryContainer: Color(0xFF98F0FF),
  onTertiaryContainer: Color(0xFF001F23),
  error: Color(0xFFBA1A1A),
  onError: Colors.white,
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  outline: Color(0xFF70787D),
  surface: _neutral98,
  onSurface: _neutral10,
  surfaceContainerHighest: Color(0xFFDCE4E9),
  onSurfaceVariant: Color(0xFF40484C),
  inverseSurface: Color(0xFF2E3132),
  onInverseSurface: Color(0xFFEFF1F3),
  inversePrimary: _gfBlue60, // lightest brand blue for FABs in dark surfaces
  shadow: Colors.black,
  surfaceTint: _gfBlue,
  outlineVariant: Color(0xFFC0C8CC),
  scrim: Colors.black,
);

/// Dark theme – dark surfaces, GF blue tints.
const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: _gfBlue60, // lighter blue stands out on dark backgrounds
  onPrimary: _gfBlueDark,
  primaryContainer: _gfBlueDark,
  onPrimaryContainer: _gfBlue60,
  secondary: Color(0xFFB4CAD5),
  onSecondary: Color(0xFF1E333C),
  secondaryContainer: Color(0xFF354A53),
  onSecondaryContainer: Color(0xFFCFE6F2),
  tertiary: Color(0xFF4DD9EC),
  onTertiary: Color(0xFF00363D),
  tertiaryContainer: Color(0xFF004E58),
  onTertiaryContainer: Color(0xFF9CF2FF),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  outline: Color(0xFF8A9296),
  surface: _neutral10,
  onSurface: _neutral80,
  surfaceContainerHighest: Color(0xFF40484C),
  onSurfaceVariant: Color(0xFFC0C8CC),
  inverseSurface: Color(0xFFE1E3E4),
  onInverseSurface: _neutral10,
  inversePrimary: _gfBlue,
  shadow: Colors.black,
  surfaceTint: _gfBlue60,
  outlineVariant: Color(0xFF40484C),
  scrim: Colors.black,
);
