name: uponorflix
description: Uponorflix VOD prototype
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  freezed_annotation: ^3.0.0
  go_router: ^15.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  sentry_flutter: ^9.0.0
  uuid: ^4.5.1
  video_local_storage:
    path: packages/video_local_storage
  video_repository:
    path: packages/video_repository

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
