name: video_local_storage
description: Hive-backed local persistence layer for the video domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.5.3
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
